spring:
  message: "Hello pcf-demo user"
  jpa:
    generate-ddl: true
server:
  port: 8802
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry.local.pcfdev.io/eureka
